included:
- kyiv-metro-ios
excluded:
- Pods

trailing_whitespace:
    ignores_empty_lines: true

disabled_rules:
  - identifier_name
  - multiple_closures_with_trailing_closure
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - first_where
  - force_unwrapping
  - operator_usage_whitespace
